---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno
spec:
  interval: 5m
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  targetNamespace: kyverno
  storageNamespace: kyverno
  releaseName: kyverno
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: '>=v3.3.0'
      sourceRef:
        kind: HelmRepository
        name: kyverno
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    reportsController:
      replicas: 1
    cleanupController:
      replicas: 1
