apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/hub-controllers
#patches:
#  - path: kyverno-values.yaml
#    target:
#      kind: HelmRelease
#      name: kyverno
