apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/hub-controllers
patches:
 - path: eso-values.yaml
   target:
     kind: HelmRelease
     name: eso
 - path: uxp-values.yaml
   target:
     kind: HelmRelease
     name: uxp
 - path: sealed-secrets-values.yaml
   target:
     kind: HelmRelease
     name: sealed-secrets
 - path: sealed-secrets-web-values.yaml
   target:
     kind: HelmRelease
     name: sealed-secrets-web
 - path: projectsveltos-values.yaml
   target:
     kind: HelmRelease
     name: projectsveltos     