---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      version: '>=2.16.2'
  test:
    enable: false
  values:
    secretName: sealed-secrets-hub-key
    fullnameOverride: sealed-secrets-controller