---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
spec:
  chart:
    spec:
      version: '>=3.1.5'
  test:
    enable: false
  values:
    deployment:
      args:
        additionalArgs:
          - --sealed-secrets-service-name=sealed-secrets-controller
    service:
      type: LoadBalancer