---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
spec:
  chart:
    spec:
      version: '>=3.1.5'
  test:
    enable: false
  values:
    sealedSecrets:
      namespace: sealed-secrets
      serviceName: sealed-secrets-controller
    service:
      type: LoadBalancer