---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
spec:
  chart:
    spec:
      version: '>=3.1.5'
  test:
    enable: false
  values:
    deployment:
      args:
        env:
          sealedSecretsControllerNamespace: sealed-secrets
          sealedSecretsControllerName: sealed-secrets-controller
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - host: sealed-secrets-web.ingress.hub.dmi-sbox.shoot.canary.k8s-hana.ondemand.com
          paths:
          - path: "/(.*)"
            pathType: Prefix