---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uxp
spec:
  chart:
    spec:
      version: '>=1.18.0-up.1'
  test:
    enable: false
  values:
    args:
    - "-d"
    packageCache:
      sizeLimit: 500Mi
