---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uxp
spec:
  chart:
    spec:
      version: '>=1.18.0-up.1'
  test:
    enable: false
  values:
    args:
    - "-d"
    packageCache:
      sizeLimit: 500Mi
    provider:
      packages:
      - xpkg.upbound.io/upbound/provider-vault:v1.0.0
      - xpkg.upbound.io/upbound/provider-helm:v0.20.0
      - xpkg.upbound.io/upbound/provider-kubernetes:v0.16.0