apiVersion: v1
kind: Namespace
metadata:
  name: hkam5z1rzf
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: hkam5z1rzf
spec:
  interval: 1m
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./flux/clusters/hkam5z1rzf/tenants
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: hkam5z1rzf-cluster-kubeconfig
  postBuild:
    substitute:
      CLUSTER_NAME: hkam5z1rzf
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: hkam5z1rzf
spec:
  dependsOn:
    - name: tenants
  targetNamespace: hkam5z1rzf
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./flux/clusters/hkam5z1rzf/infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-background-controller
      namespace: kyverno
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-background-controller
      namespace: kyverno
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno-reports-controller
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets
      namespace: eso
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets-cert-controller
      namespace: eso
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets-webhook
      namespace: eso     
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: hkam5z1rzf-cluster-kubeconfig
        - op: add
          path: /spec/serviceAccountName
          value: flux-cluster-admin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: hkam5z1rzf
spec:
  dependsOn:
    - name: infra-controllers
  targetNamespace: hkam5z1rzf
  interval: 1m
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./flux/clusters/hkam5z1rzf/apps
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: hkam5z1rzf-cluster-kubeconfig
        - op: add
          path: /spec/serviceAccountName
          value: flux-restricted
