apiVersion: v1
kind: Namespace
metadata:
  name: hub
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hub-tenants
  namespace: hub
spec:
  interval: 1m
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./flux/clusters/hub/tenants
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: hub-cluster-kubeconfig
  postBuild:
    substitute:
      CLUSTER_NAME: hub
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hub-controllers
  namespace: hub
spec:
  dependsOn:
    - name: hub-tenants
  targetNamespace: hub
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  path: ./flux/clusters/hub/hub-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: access-manager
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: addon-controller
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: classifier-manager
      namespace: projectsveltos
    # - apiVersion: apps/v1
    #   kind: Deployment
    #   name: conversion-webhook
    #   namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: event-manager
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: hc-manager
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: sc-manager
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: shard-controller
      namespace: projectsveltos
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets
      namespace: eso
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets-cert-controller
      namespace: eso
    - apiVersion: apps/v1
      kind: Deployment
      name: eso-external-secrets-webhook
      namespace: eso      
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: hub-cluster-kubeconfig
        - op: add
          path: /spec/serviceAccountName
          value: flux-cluster-admin
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hub-configs
  namespace: hub
spec:
  dependsOn:
    - name: hub-controllers
  targetNamespace: hub
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: false
  path: ./flux/clusters/hub/hub-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: hub-cluster-kubeconfig
  postBuild:
    substitute:
      vault_server: "https://vault-staging.tools.sap"
      vault_path: "eso-vault"     