apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-policies-helm-repo.yaml
  - kyverno-policies-helm-release.yaml

patches:
  - path: kyverno-policies-helm-release.yaml
    target:
      kind: HelmRelease
      name: ${KYVERNO_CPOL_RELEASE_NAME:kyverno-policies}
configMapGenerator:
  - name: cpol-helm-chart-value-overrides
    files: 
      - values.yaml=cpol-helm-chart-value-overrides.yaml
configurations:
  - kustomizeconfig.yaml
