apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      version: ">=6.7.1"
  test:
    enable: false
  values:
    replicaCount: 5
    ingress:
      hosts:
        - host: podinfo.hkam5z1rzf
          paths:
            - path: /
              pathType: ImplementationSpecific
