apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  targetNamespace: keda
  storageNamespace: keda
  releaseName: keda
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3