---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
spec:
  targetNamespace: kyverno
  storageNamespace: kyverno
  releaseName: kyverno
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: '>=v3.3.0'
      sourceRef:
        kind: HelmRepository
        name: kyverno
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3