apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projectsveltos/helm-repo.yaml
  - projectsveltos/helm-release.yaml
  - eso/helm-repo.yaml
  - eso/helm-release.yaml
  - upbound/helm-repo.yaml
  - upbound/helm-release.yaml
  - sealed-secrets/helm-repo.yaml
  - sealed-secrets/helm-release.yaml
  - sealed-secrets-web/helm-repo.yaml
  - sealed-secrets-web/helm-release.yaml  