apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: default
spec:
  targetNamespace: policy-reporter
  storageNamespace: policy-reporter
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
  interval: 5m
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
