apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: policy-reporter
  namespace: default
spec:
  interval: 5m
  url: https://kyverno.github.io/policy-reporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${POLICY_REPORTER_RELEASE_NAME:policy-reporter}
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: policy-reporter
  storageNamespace: policy-reporter
  releaseName: ${POLICY_REPORTER_RELEASE_NAME:policy-reporter}
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: policy-reporter
      version: ${POLICY_REPORTER_CHART_VERSION:3.0.0-rc.13}
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
