---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  targetNamespace: kyverno
  storageNamespace: kyverno
  releaseName: kyverno-policies
  interval: 1m
  chart:
    spec:
      chart: kyverno-policies
      version: '>=v3.3.0'
      sourceRef:
        kind: HelmRepository
        name: kyverno-policies
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
