---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno-policies
  namespace: default
spec:
  interval: 5m
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: kyverno-policies
  storageNamespace: kyverno-policies
  releaseName: kyverno-policies
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: kyverno-policies
      version: '>=v3.3.0'
      sourceRef:
        kind: HelmRepository
        name: kyverno-policies
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
