---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: eso
spec:
  chart:
    spec:
      version: '>=0.10.5'
  test:
    enable: false
  values:
    replicaCount: 2
    webhook:
      replicaCount: 2
    certController:
      replicaCount: 2
