apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/infra-controllers
patches:
  - path: kyverno-values.yaml
    target:
      kind: HelmRelease
      name: kyverno
  - path: eso-values.yaml
    target:
      kind: HelmRelease
      name: eso       
  - path: keda-values.yaml
    target:
      kind: HelmRelease
      name: keda
configMapGenerator:
  - name: reloader-helm-chart-value-overrides
    files:
      - values.yaml=reloader-helm-chart-value-overrides.yaml
configurations:
  - kustomizeconfig.yaml
