---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      version: '>=v1.1.0'
  test:
    enable: false
  valuesFrom:
  - kind: ConfigMap
    name: reloader-helm-chart-value-overrides
