---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
spec:
  chart:
    spec:
      version: '>=2.15.2'
  test:
    enable: false
  values:
    operator:
      replicaCount: 2
    webhooks:
      replicaCount: 2
    metricsServer:
      replicaCount: 2