apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/infra-controllers
patches:
  - path: kyverno-values.yaml
    target:
      kind: HelmRelease
      metadata:
        name: kyverno
  - path: eso-values.yaml
    target:
      kind: HelmRelease
      metadata:
        name: eso       
  - path: keda-values.yaml
    target:
      kind: HelmRelease
      metadata:
        name: keda