---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  chart:
    spec:
      version: '>=3.3.0'
  test:
    enable: false
  values:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 2
    reportsController:
      replicas: 2
    cleanupController:
      replicas: 3
