---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      version: '>=v1.1.0'
  test:
    enable: false
  values:
    reloader:
      deployment:
        replicas: 2
