apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  targetNamespace: sealed-secrets
  storageNamespace: sealed-secrets
  releaseName: sealed-secrets
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  interval: 5m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
