apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policy-reporter-ks
  namespace: policy-reporter
spec:
  targetNamespace: default
  interval: 5m
  timeout: 10m
  path: "./flux-kustomize/infra-addons/policy-reporter"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  kubeConfig:
    secretRef:
      key: kubeconfig
      name: ${KUBECONFIG_PATH:admin-kubeconfig-kyma-dev-eu12-poc-pls}
