---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: default
spec:
  interval: 5m
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: kyverno
  storageNamespace: kyverno
  releaseName: kyverno
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: kyverno
      version: '>=3.3.x'
      sourceRef:
        kind: HelmRepository
        name: kyverno
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
