apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-web
spec:
  targetNamespace: sealed-secrets-web
  storageNamespace: sealed-secrets-web
  releaseName: sealed-secrets-web
  chart:
    spec:
      chart: sealed-secrets-web
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-web
  interval: 5m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3