apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-connection
spec:
  provider:
    vault:
      server: "${VAULT_SERVER}"
      path: "${VAULT_PATH}"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "${VAULT_MOUNT_PATH}"
          role: "eso"
          serviceAccountRef:
            name: eso
            namespace: eso
