apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uxp
spec:
  targetNamespace: upbound-system
  storageNamespace: upbound-system
  releaseName: upbound-system
  chart:
    spec:
      chart: universal-crossplane
      sourceRef:
        kind: HelmRepository
        name: upbound-stable
  interval: 5m
  timeout: 5m
  upgrade:
      retries: 3