apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-connection
spec:
  provider:
    vault:
      server: ${vault_server}
      namespace: "i503158/dmi-sbox"
      path: ${vault_path}
      version: "v2"
      auth:
        kubernetes:
          mountPath: ${vault_path}
          role: "eso-vault-role"
          serviceAccountRef:
            name: eso-vault-sa
            namespace: eso
          secretRef:
            name: eso-vault-token
            key: "token"
            namespace: eso
