apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-connection
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "eso-vault"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "eso-vault"
          role: "eso-vault-role"
          serviceAccountRef:
            name: eso-vault-token
            namespace: eso