apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno/helm-repo.yaml
  - kyverno/helm-release.yaml
  - kyverno-policies/helm-repo.yaml
  - kyverno-policies/helm-release.yaml
