apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno/kyverno.yaml
#  - kyverno-policies/kyverno-policies.yaml

# patches:
# - target:
#     kind: HelmRelease
#     name: kyverno
#   patch: |-
#     - op: replace
#       path: /spec/releaseName
#       value: kyverno-patched
#     - op: replace
#       path: /spec/chart/spec/version
#       value: 3.4.0
# - target:
#     kind: HelmRelease
#     name: kyverno-policies
#   patch: |-
#     - op: replace
#       path: /spec/releaseName
#       value: kyverno-patched
#     - op: replace
#       path: /spec/chart/spec/version
#       value: 3.4.0
