apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-helm-repo.yaml
  - kyverno-helm-release.yaml

patches:
  - path: kyverno-helm-release.yaml
    target:
      kind: HelmRelease
      name: ${KYVERNO_RELEASE_NAME:kyverno}
configMapGenerator:
  - name: kyverno-helm-chart-value-overrides
    files: 
      - values.yaml=kyverno-helm-chart-value-overrides.yaml
configurations:
  - kustomizeconfig.yaml
