apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-core-CLUSTER
  namespace: default
spec:
  interval: 15m
  path: "./infra-core"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno-CLUSTER
      namespace: default
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno-policies-CLUSTER
      namespace: default
  timeout: 5m
  kubeConfig:
    secretRef:
      key: kubeconfig
      name: admin-kubeconfig-CLUSTER
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-addons-CLUSTER
  namespace: default
spec:
  dependsOn:
    - name: infra-core
  interval: 15m
  path: "./deploy/infra-addons"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: eso-CLUSTER
      namespace: default
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: policy-reporter-CLUSTER
      namespace: default
  timeout: 5m
  kubeConfig:
    secretRef:
      key: kubeconfig
      name: admin-kubeconfig-CLUSTER
