---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-repo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/linuxbsdfreak/multi-cluster
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-core
  namespace: default
spec:
  targetNamespace: default
  interval: 5m
  timeout: 10m
  path: "./flux-kustomize/infra-core"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ${KYVERNO_RELEASE_NAME}
      namespace: default
  postBuild:
    substitute:
      KYVERNO_RELEASE_NAME: "kyma-dev-eu12-poc-pls-wps-kyverno"
      KYVERNO_CHART_VERSION: "3.3.4"
      KUBECONFIG_PATH: "admin-kubeconfig-kyma-dev-eu12-poc-pls"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cpol
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: infra-core
  interval: 5m
  timeout: 10m
  path: "./flux-kustomize/infra-cpol"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ${KYVERNO_PSP_CPOL_RELEASE_NAME}
      namespace: default
  postBuild:
    substitute:
      KYVERNO_PSP_CPOL_RELEASE_NAME: "kyma-dev-eu12-poc-pls-wps-cpol"
      KYVERNO_PSP_CPOL_CHART_VERSION: "3.3.2"
      KUBECONFIG_PATH: "admin-kubeconfig-kyma-dev-eu12-poc-pls"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-addons
  namespace: default
spec:
  targetNamespace: default
  dependsOn:
    - name: infra-cpol
  interval: 5m
  timeout: 5m
  path: "./flux-kustomize/infra-addons"
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-repo
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ${ESO_RELEASE_NAME}
      namespace: default
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ${POLICY_REPORTER_RELEASE_NAME}
      namespace: default
  postBuild:
    substitute:
      ESO_RELEASE_NAME: "kyma-dev-eu12-poc-pls-wps-eso"
      ESO_CHART_VERSION: "0.11.0"
      POLICY_REPORTER_RELEASE_NAME: "kyma-dev-eu12-poc-pls-wps-reporter"
      POLICY_REPORTER_CHART_VERSION: "3.0.0-rc.13"
      KUBECONFIG_PATH: "admin-kubeconfig-kyma-dev-eu12-poc-pls"
