---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: policy-reporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
      version: '>0.0.0'
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: policy-reporter
  targetNamespace: policy-reporter
